version: '3.7'
services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
  node-app:
    build:
      context: .
      target: development
      # args:
      #   - NODE_ENV=development

    volumes:
      # - ./:/app
      # - /app/node_modules
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
